version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo "Zipping deployment package..."
      - zip -r nodejs.zip node_modules index.mjs
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name postMock837Claims --zip-file fileb://nodejs.zip
      - echo "DONE!!"
      - echo Build started on `date`
artifacts:
  files:
    - nodejs.zip
